name: Build and run

on: [push, pull_request]

jobs:
  build-and-run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Compile executable
      run: |
        autoreconf -if
        ./configure
        make

    - name: Run executable
      run: ./remap
